### ISSUE TITLE
App installed from FDroid wants to update in Play Store

### ISSUE THREAD

**Issue by bluezed** [jamie-mh/AuthenticatorPro#1054]
**Describe the bug**
I have v 1.23.0 installed through FDroid (IzzyOnDroid) and since this morning Google Play Store is trying to auto-update the app but fails obviously.

**To Reproduce**
Install the app from FDroid then go to Play Store and search for updates. 

**Expected behavior**
Play Store should not try to update the app.

**App Version**
1.23.0 F-Droid

![Screenshot_2023-12-16-08-38-02-425_com android vending](https://github.com/jamie-mh/AuthenticatorPro/assets/3831765/3ed0e798-496a-414d-8bfe-f5b703ff1335)

**Comment by KarlKarp** [comment]
Right description. 
Android 14 Patch 01.12.2023
Version 1.23.0 F-Droid

**Comment by MagicLike** [comment]
This is actually expected behaviour, as apps from F-Droid / certain F-Droid repos are getting signed with a different key than the Google Play build. Android refuses to updated an app when the signature of the current installed version doesn't match with the new version and therefore throws an error. I don't know how @izzysoft handles signing the APKs delivered through his repo, but I guess the key / signature difference could be the simple cause for the error.

**Comment by IzzySoft** [comment]
No. I take the APKs signed by the corresponding developers (the very same ones you distribute here).

Google Play is on a hijack spree currently, trying to replace all apps with their PlayStore pendants – which according to its own rules is a no-go. If even the signature does not match, it should not attempt that at all *knowing* it would fail (though I wouldn't put it beyond them to work around that security measure; their framework running with system permissions would have the power to do that). Otherwise it should respect the `installer` – which is a property saying where the app was installed from. If that is set to `org.fdroid.fdroid` (so the app was installed using the official F-Droid client), and an app by that name is available on the device, it should not touch the app.

So this is not something @MagicLike or I can solve – you need to complain to Google about that. And if you know how and where, bring it to the attention of the proper authorities, who should fine Google for that hijacking heftily, as it's once more an abuse of their monopoly intended to cement that monopoly. I can no longer believe it's an oversight or a bug in the PlayStore app, this is going on much too long already for that.

**Comment by bluezed** [comment]
@IzzySoft thanks a lot for explaining.
I'm a bit shocked as it's the first time I've come across this and I've had many apps from FDroid installed for years now and most of them are on PlayStore too...

Any ideas where and how to report this to Google and what the official channels in the EU would be?

**Comment by IzzySoft** [comment]
Unfortunately neither: I've left the Google EcoSystem years ago and run my devices without their framework (so no PlayStore, no GMS etc). As for the "official channels", I know there are ongoing anti-trust cases and wonder if that has not brought up anywhere. As massive as they push those apps lately it can hardly have been missed.

**Comment by jamie-mh** [comment]
Hi,

This could be simply due to the way that the version codes are handled.

For example, in the latest release 1.23.0:

```
100000091 -> AAB (Play Store)
 41000091 -> APK (F-Droid ARM64 variant)
  1000091 -> APK (F-Droid all ABIs)
```

Since 100000091 > 41000091, it probably works on the (incorrect) assumption that it's out of date and can be updated via Google Play. I might not even check the signatures, hence why it fails.

Indeed, if I align the versions on my device, an update is no longer prompted. I'll see if I can tweak the build process to make sure that the F-Droid version codes are >= than the Google Play ones.

**Comment by jamie-mh** [comment]
This should no longer be an issue in release 1.24.0.

**Comment by bluezed** [comment]
I just got the update on FDroid and I can confirm that it's no longer showing up in PlayStore.
Thank you very much @jamie-mh for finding the problem and solving it 😀

@IzzySoft maybe this fix can help with the other affected apps as well?

**Comment by IzzySoft** [comment]
@bluezed I'll send out a toot for that, thanks! Already had marked the comment and was just waiting for confirmation. Good to see what triggers the mess, so we at least have a way to avoid that.

**Comment by IzzySoft** [comment]
So [here's the toot](https://floss.social/@IzzyOnDroid/111669457762275832) making my 4k followers aware :smiley: (boosts already started spreading the word further) Thanks again for figuring the cause of this mess!
