### ISSUE TITLE
Icon request: https://bootstrap.academy/

### ISSUE THREAD

**Issue by Cameo007** [jamie-mh/AuthenticatorPro#1106]
Please fill out the fields below where applicable:

**Name of website / service:**
https://bootstrap.academy/

**Comment by Kvasenok** [comment]
Hi @Cameo007 
Bootstrap Academy doesn't meet the requirements to have the icon added, the service is not within SimilarWeb's Top 200k Global Raiting. Because of this the icon(s) can be added only if @jamie-mh approves it.
In the meantime you can take the icons below for your personal use in the app.
![bootstrapacademy_dark](https://github.com/jamie-mh/AuthenticatorPro/assets/44749170/8c233379-54a7-4e4c-9504-d87f3b0e66ad)
![bootstrapacademy](https://github.com/jamie-mh/AuthenticatorPro/assets/44749170/e5b67f6d-0d0e-46f2-ba90-99184c6054d7)

**Comment by jamie-mh** [comment]
Hi,

As said by @Kvasenok , the current rank is 856,942 on Similarweb which to too low to be added as an icon.

Cheers
