### ISSUE TITLE
WearOS Sync independent

### ISSUE THREAD

**Issue by ArtemiisFowl** [jamie-mh/AuthenticatorPro#1137]
**Is your feature request related to a problem? Please describe.**
WearOS App does only worm if phone AND wear App are installed from PlayStore. I wish that google-free variants (f-droid/apk on github) offer the same functionality.
For now the wearOs apk in github seems to be useless.

**Describe the solution you'd like**
Implement an easy own "phone to watch" sync mechanism. This could be manually or by changing something on the phone. Or allow to import an backup file on the watch to use it independent.

**Comment by jamie-mh** [comment]
Your issue describes two different things.

The F-Droid builds do not contain any Google services so they can't work with Wear OS. However, if you don't want to use Google Play, you can use the "me.jmh.authenticatorpro.apk" and "me.jmh.authenticatorpro.wearos.apk" files from the GitHub releases and they will work together.

I don't plan to make the Wear OS app work independently because I think there are few people who would be willing to use ADB to transfer a backup file and restore it on their watch.

Cheers

**Comment by ArtemiisFowl** [comment]
Thanks for clarification.
I installed the phone app from f-droid and used the wearOs apk from github. My misunderstanding explains the use of the github apks. They are just a copy of playStore versions (both with google services).

I can understand that the user group is to small for google independent wearOs sync.

All the best!
