### ISSUE TITLE
Automatic sync/backup secret to any cloud drive (like Google Drive)

### ISSUE THREAD

**Issue by bestpika** [jamie-mh/AuthenticatorPro#16]
Could the app add an automatic sync/backup function?
This way users don't have to worry about forgetting to back up the secret.

Thank you.

**Comment by jamie-mh** [comment]
Hi @bestpika,

I can't see this happening because the implementation would require the Internet permission and the use of an intrusive Google Drive SDK. For a privacy and security focused app, this perhaps isn't a good idea.

**Comment by jamie-mh** [comment]
An alternative might be to remind the user to make a backup if they haven't made one in a while.

**Comment by bestpika** [comment]
@jamie-mh Remind user sound's a good idea.
Or could it automatic backup to the device's local storage, let me can use another app to automatically upload it to my cloud drive?

**Comment by jamie-mh** [comment]
In the next version of Android, this might not be possible, see: [https://developer.android.com/preview/privacy/storage](https://developer.android.com/preview/privacy/storage). This change prevents apps from accessing data in other apps.

I think a reminder to backup is the best solution for the time being.

**Comment by bestpika** [comment]
@jamie-mh This change appears to only affect the app's private storage area?

**Comment by jamie-mh** [comment]
@bestpika 

I don't think it's possible to save a file automatically in the background without special permissions [https://developer.android.com/preview/privacy/storage#all-files-access](https://developer.android.com/preview/privacy/storage#all-files-access). Otherwise the app will need to open a save dialog first. Once the Xamarin SDK is updated for Android 11, I will investigate further.

**Comment by Michounet** [comment]
I would also love this feature but only if it doesn't require more app permissions (people are suspicious when an app starts asking for too many permissions) and security is not compromised or reduced.

It's not a priority for me because I use another app to automatically sync the backup file regularly to Google Drive, so I only need to make a new backup when something has changed. This is something you might want to check. Also, when I make a new backup I'm prompted which app I want to use to store it so if it would be possible to "pass it" to the Google Drive app (right now it only allows me to select file managers) that would do the trick.

By the way, I can choose the MiXplorer Silver file manager to select where to store the file and it does allow mapped "remote file systems" (network shares, ftp/scp, Google Drive). I haven't tried it, but maybe you can store the file directly on any remote destination that way.

**Comment by exterrestris** [comment]
Perhaps an option that could satisfy both privacy and the ability to sync via the cloud could be to have a second 'plugin' app that does the actual syncing? That way, those who don't need/want cloud sync keep the app as is with the existing required permissions intact, and those that do can install the second app that has the requisite permissions to be able to sync to the cloud as well

**Comment by jamie-mh** [comment]
@exterrestris ,

Indeed, this is a good idea. However, on Android this is impossible. As a security measure, an app cannot read the private data of another app. So a secondary app has no way of reading the database and uploading a backup.

However, it might be possible to write backups to the device storage periodically, and have them auto-uploaded to cloud storage through another app. I need to investigate this further.

**Comment by exterrestris** [comment]
I'm reasonably sure I've used an app with that architecture before, but unfortunately I cannot recall which app it was. It is likely to have been some time ago when Android had fewer restrictions, so I can understand that more recent versions of Android might make it difficult/impossible to do. However, thinking about it did remind me of a current app I use on a couple of my devices which takes a slightly different approach: [Automate](https://play.google.com/store/apps/details?id=com.llamalab.automate). They maintain all the functionality in the main app, but use extension apps to grant permissions like network access - the main app on its own cannot access the network as it doesn't have the permissions itself

**Comment by MaluNoPeleke** [comment]
If Authenticator Pro would save the backup locally automatically it could be programmed with Tasker or Automate to be uploaded with specific rules.

**Comment by jamie-mh** [comment]
Hi,

In the latest release (1.13), an auto-backup feature has been included. This will automatically create encrypted (or not) backups on the device storage or other storage locations. An automation or sync app would be able to upload the backups to cloud. I will write a page on the subject on the project wiki for those interested.

As it's unlikely that I will add a direct cloud sync because of issues mentioned above, I'll consider this issue resolved for now.

**Comment by splitbrain** [comment]
Does this implement auto import too? Because otherwise it's not possible to actually set up meaningful syncing between two devices?

**Comment by jamie-mh** [comment]
No, it only supports backing up at the moment. But adding an auto restore feature might be something worth adding in the next release. As long as the backup location is bidirectionally synced, it could automatically restore the latest backup if necessary.

**Comment by GintokiHub** [comment]
> Perhaps an option that could satisfy both privacy and the ability to sync via the cloud could be to have a second 'plugin' app that does the actual syncing? That way, those who don't need/want cloud sync keep the app as is with the existing required permissions intact, and those that do can install the second app that has the requisite permissions to be able to sync to the cloud as well

This might be far-away and a bit dreamy of a request / feature request ( I get this would probably be really labour intensive so I am in no way saying this would need to be there)

Some kind of synching-plugin specific or similar tech which would allow people to setup such an environment, through a plug-in or if at all possible somehow a system which would make this easier to setup then synchthing normally is to make it more user accessible would be amazing.

**Comment by GintokiHub** [comment]
> I'm reasonably sure I've used an app with that architecture before, but unfortunately I cannot recall which app it was. It is likely to have been some time ago when Android had fewer restrictions, so I can understand that more recent versions of Android might make it difficult/impossible to do. However, thinking about it did remind me of a current app I use on a couple of my devices which takes a slightly different approach: [Automate](https://play.google.com/store/apps/details?id=com.llamalab.automate). They maintain all the functionality in the main app, but use extension apps to grant permissions like network access - the main app on its own cannot access the network as it doesn't have the permissions itself

If one of you guys has made the tasker or automate  / iftt + / similar setup and it is possible within the aforementioned app to share the "recipe"  of the setup it would be great if that someone could share it here and perhaps eventually be hyperlinked in the app somewhere?

**Comment by p1ratrulezzz** [comment]
> > I'm reasonably sure I've used an app with that architecture before, but unfortunately I cannot recall which app it was. It is likely to have been some time ago when Android had fewer restrictions, so I can understand that more recent versions of Android might make it difficult/impossible to do. However, thinking about it did remind me of a current app I use on a couple of my devices which takes a slightly different approach: [Automate](https://play.google.com/store/apps/details?id=com.llamalab.automate). They maintain all the functionality in the main app, but use extension apps to grant permissions like network access - the main app on its own cannot access the network as it doesn't have the permissions itself
> 
> If one of you guys has made the tasker or automate / iftt + / similar setup and it is possible within the aforementioned app to share the "recipe" of the setup it would be great if that someone could share it here and perhaps eventually be hyperlinked in the app somewhere?

As for me I use AutoSync + OneDrive (Google, Dropbox and etc, lot of supported providers) and use Autobackup and Autorestore feature of the app.
