### ISSUE TITLE
Suggestion: Support for custom icons

### ISSUE THREAD

**Issue by bonn2** [jamie-mh/AuthenticatorPro#22]
Would it be possible to add the option to add custom .ico files. Would come in handy with things like 2fa on custom amp instances. Along with other more niche websites that have 2fa

**Comment by jamie-mh** [comment]
Hi @bonn2 ,

I've looked into this in the past. There are however a few issues I have yet to figure out that make this tricky, mostly due the way the app is structured currently.

For instance:
- How to deal with backups, the custom icons would need to be embedded somehow. They might not look very nice on another device due to different screen densities.
- How to deal with both night and dark modes, custom icons might not work very well. There might be a bit of processing required on these icons beforehand.
- How to sync the images to the Wear OS app, it could be too much data to send at once.
- etc...

It may certainly be possible, but at the moment there is no easy way of making it work.

As a compromise for the time being perhaps, how about custom "generic" icons in various colours, this might be a good addition to the list. And of course if you have any icon suggestions, I'm all ears.

**Comment by bonn2** [comment]
Alright, I was thinking it could work similarly to Keepass where they embed it in their database. Also maybe have them stored on the watch instead of being synced each time. For now I'll gather the few I need and submit a separate issue.

**Comment by jamie-mh** [comment]
I'll keep this issue open for now, I won't rule this feature out entirely. It needs a bit more planning.

**Comment by jamie-mh** [comment]
Ok, figured it out. Custom icons are now supported in release 1.9.0.
