### ISSUE TITLE
Some doubts + suggestions + Icon requests

### ISSUE THREAD

**Issue by salman-q** [jamie-mh/AuthenticatorPro#26]
1. I want to know if there is any way to recover my tokens using the backup file created by the app or in general any other way?

2. Your app doesn't ask for the "Storage" permission. How is it able to write the backup file to my storage then?

3. It would be great if you could integrate some generic icons like in KeePass database. You don't have to search which ones to integrate. Just copy the KeePass list. It's very complete and adaptable

4. There are some UI suggestions I have to make. Since I can't take screenshots in the app, I'll try to explain in words.

Make the top bar of the app static which displays the current category being shown. It solves two problems at once and improves the usability.

First, when I scroll down to see all the tokens, the tokens go up and slide down under my status bar which is translucent. The content of the app and the status bar collides (one is on top of the other) which isn't very aesthetically pleasing.

Second, if the top bar is static, the users would know, at all times, which category is being displayed. This isn't a big issue for me as I normally don't need to know this information but I assume someone with a large number of tokens might. Even if you don't make the top bar static, at least make it so that app content doesn't go under the phone's status bar.

My preferred solution is to hide the status bar as soon as the app open if that is possible.

5. Another aesthetic suggestion would be to make the timer animation continuous rather than ticking. It feels less burdened and greatly improves the seamlessness. You can also offer an option for a round timer on the right hand side of each token kind of like Google Authenticator. Also since the timer is synced for each entry, why not make a universal timer which stays static on top?

6. Any love for a grid view? (See Twilio Authy)

Finally, here are two icon requests. I'd be grateful.

https://www.grammarly.com/

https://wetransfer.com/

Great work!

P.S.: This is my first time writing something on GitHub.

**Comment by jamie-mh** [comment]
Hi @salman-q ,

I've added those two icons, they'll be included in the next update.

1. Yes, you can get the tokens from a backup. If you create a backup without a password, it will be unencrypted and displayed in plain text. If you open this file with a text editor you will find something in this format: https://github.com/jamie-mh/AuthenticatorPro/blob/master/README.md#backup-file-format . The token is in the "Secret" field.

2. In order to write and read backups, the app uses something called the "Storage Access Framework", this is a mechanism built into Android to read and write files. Since this is an explicit user action, it doesn't ask for permissions, it would be redundant. It only grants temporary access to files for reading and writing.

3. Yes, this is a good idea. This was also discussed in #22.

4. As far as UI stuff goes, I understand what you're saying. The top bar used to be static, but since a bar was added at the bottom, it made sense to hide it. Having two bars on the screen when scrolling is a little annoying when scrolling in a long list. The issue with Android is that when you want to display stuff behind the status or navigation bar, things can get very buggy. Depending on your device, the status bar might look totally different. In fact, it looks fine on my device, but I don't know about yours. Also, I don't believe it is possible to hide just the status bar, Android only lets you hide both the status and navigation at the same time. But I'll have another look at this and see what I can do.

5. I have experimented with making the progressbar smooth, it actually looked rather strange. I also tried making a round timer circle, but I didn't feel it looked significantly better than the current solution, but I will give it another go. Also, the reason why there is no universal timer, is that not all entries are necessarily synced. I have a few that need to run on a shorter timer.

6. I've never used Authy, but it seems like a totally different UI. Probably too much effort to have both.

Let me know if this answers your questions.

**Comment by salman-q** [comment]
Yes. That answers about everything. I get what you are saying about the timer UI and the top bar. I guess the current option is the best solution.

But about the grid view, I am of the opinion that it would be an instant hit. What I am imagining is something like Google Keep thumbnail view if you have used it. Anyway, I am pretty satisfied with what I have right now. Just wanted to let you know.

Thank you for the icons. I'd be looking forward to the generic icons integration. You can close this now.

**Comment by jamie-mh** [comment]
I've added a few generic icons to the list. This should help fill a some gaps.
I'll look into implementing a grid view.
