### ISSUE TITLE
Option to use "insecure" storage

### ISSUE THREAD

**Issue by haarp** [jamie-mh/AuthenticatorPro#3]
Hello,

nice app! Would you consider adding an option to use regular data storage inside /data? The reason is that the secure storage method makes backups impossible from outside the app. Yes, the app itself has a backup option, but that can't be automated like the general device-wide backup I am running. A good backup is a frequent backup, and having to manually interact for each backup is not an option.

Thanks!

**Comment by jamie-mh** [comment]
Hi @haarp,

I don't know if that would be a good idea. In order for the database to be backed up, it would need to be unencrypted. The issue is that any app with the storage permission would potentially be able to access your authenticator secret keys.
If it were encrypted there would need to be an option to set the database key manually (at the moment it's randomly generated on first launch) and then override the generated key when you want to restore it.

It might be possible but it seems a bit complex for a niche feature like this. At the moment, I generally create a backup to my Google Drive everytime I add a new authenticator to the list. It's not something I need to do often anyway.

Thanks for your feedback. I will investigate this further but I can't guarantee that it will be implemented. Sorry!

**Comment by haarp** [comment]
> The issue is that any app with the storage permission would potentially be able to access your authenticator secret keys.

Is this really true? As far as I know, the storage permission only concerns SD storage (or whatever it's called nowadays). Even with that permission, apps still cannot read another apps' stuff in `/data/data`.

Root will of course be able to read that file. But root is also able to read or manipulate memory of running apps, so there's no effective way to protect against it anyway.

Unencrypted storage in /data would be fine, I think, as long as an ignorant user is sufficiently discouraged from enabling it.

**Comment by jamie-mh** [comment]
Hmmm, maybe I'm confused. I don't personally use a backup application myself so I'm not sure how it works. If an app cannot access another app's data directory, how does a backup app read it?

**Comment by haarp** [comment]
My backup "app" uses root rights to do it. The popular classic, Titanium Backup, also uses root to do backups.

**Comment by jamie-mh** [comment]
Ok, I'll see if I can implement this in the next update.

**Comment by haarp** [comment]
Whoo, thank you!

**Comment by jamie-mh** [comment]
@haarp 

The latest release now has a setting to decrypt the database. I've tested it myself with Titanium Backup and it works as expected. The update is currently under review on Google Play, so it should come through in a few days.

When you get the update let me know if it works for you.

**Comment by haarp** [comment]
Just tested the newest version from Izzy's repository. It's working, I can now grab and backup proauth.db3. Thanks a lot!
