### ISSUE TITLE
Yandex.Key support

### ISSUE THREAD

**Issue by maxiikk** [jamie-mh/AuthenticatorPro#318]
Hey, ive noticed that the authenticator doesnt support yandex.key, and it would be great if it did, cuz yandex is a "360" ecosystem that has everything for you just with one account.
I saw KeePassOTP  encounter the same problem and they found an add-on named KeeYa OTP on github which seemed to have worked
Could you see how it works and maybe integrate it? Would be great, thanks
Yandex.Key doesnt need internet access so it would fit in Authenticator Pro

Link to KeeYaOTP plugin for KeePassOTP: https://github.com/norblik/KeeYaOtp

**Comment by Kvasenok** [comment]
This would be a great feature! Since Yandex uses its special TOTP method it requires users to download their yandex.key app which also supports basic TOTP, hence the users who use Yandex services are generally using the yandex.key app for all their TOTP needs as they don't have much choice.
Since Authenticator Pro already supports Blizzard and Steam TOTP, adding the Yandex one shouldn't be too hard and it would increase the number of users because many people are switching to Yandex nowdays.

**Comment by monolit** [comment]
sorry for dumb question, how to get yandex secret
