### ISSUE TITLE
Scanned QR codes aren't added

### ISSUE THREAD

**Issue by Michounet** [jamie-mh/AuthenticatorPro#46]
I've been migrating all my two factor authentication codes from _Protectimus_ to _Authenticator Pro_ because it's far superior and has a backup feature which I think is crucial. I added a few sites weeks ago and today when I tried to add two more sites (Epic Games Store and GitHub) it doesn't work. This is what happens:

1. I open Authenticator Pro
2. I click on the "+" sign
3. I select _"Scan a QR Code"_
4. The camera goes on, I point at the QR code
5. The phone makes a short vibration, a _"There have been changes made since your last backup."_ message is shown, but no new entry is added, no other message is shown (either an error or a success notifications)

Entering the information manually works but of course it's more tedious than scanning the QR code. It did work fine a month ago (I've just checked and my last backup is from July, 13th and I've also noticed that there was a new version released on August, 14th).

I'm using latest version from Google Play Store (1.9.2) and my phone is a Xiaomi Mi 9T Pro.

By the way, I also wish to take this opportunity to thank you for developing this app!

**Comment by jamie-mh** [comment]
Hi @Michounet ,

Thanks for pointing this out. I can reproduce this issue with some QR codes.
If you disable backup reminders in the settings, you should see an error message when scanning codes. The two messages interfere with eachother.

Since this is a slightly annoying bug, I've pushed a small update to Google Play.
It will be available once it is approved by the moderators.
