### ISSUE TITLE
No Cloud Backup Option?

### ISSUE THREAD

**Issue by matt873** [jamie-mh/AuthenticatorPro#487]
There is no cloud backup option in app although it's mentioned as one of it's feature here on github. Am I not being able to find it or this feature is missing from the app?

**Comment by RobertHarnett** [comment]
You have to manually backup the file yourself:

1. Hit the burger menu button in the apps main screen.
2.  Select 'backup', you can choose which format you wish to save your codes in.
3. Once selected it will open your devices file menu. I believe this might be slightly different device to device but for me if I select the menu icon I can select 'Drive' or any other cloud storage service I have set up on my phone. 
4. I can then save it to my cloud storage.

Note you merely save the backup file itself to a cloud provider of your choosing. Authenticator Pro does not operate it's own cloud backup service as this is logistically very difficult, costly, increases potential security vulnerabilities, and crucially is not what Authenticator Pro is about. This app is an offline secure vault that gives the user full manual control over their data.

I myself used to use 'Authy', a service that has user accounts and backs up 2FA codes automatically to the cloud. I decided to move off of this as It was closed source, and I had no idea how secure my 2FA codes were.

I was essentially giving Authy full control and access to my codes. 

Yes it was perhaps more convenient at times but negated the whole purpose of 2FA codes which is something only I should have access to. I switched to Authenticator Pro as I know _what happens in the app stays in the app_ and _only I have access_ to them. I also know when I then backup my codes to the cloud using the encrypted format that the encryption is happening on my device before being put on Google drive, this means I'm safe knowing google has no access to be able to read my codes. I couldn't say the same for Authy as I had no idea how my data and codes were handled.

Ultimately there are many 2FA services that offer integrated cloud backups but they come at the expense of security and huge amounts of trust in third party services. It's a bit like setting all your passwords to '12345'. Yes it might be more convenient and easier then a difficult to remember password but it forgoes a lot of the benefits and security of a password to begin with.

Its a choice you have to make yourself between convenience and security. Personally I felt if I was going through the effort of 2FA on my accounts I might as well make sure it's private and secure, otherwise it negates the whole purpose of 2FA to begin with, hence why I left Authy for Authenticator Pro.

**Comment by Jnss98b** [comment]
I think the developer should still add an option to automatically backup to a cloud provider of your choice though, similar to how an app like swift back up does. 
![Screenshot_20220729-030211~2](https://user-images.githubusercontent.com/24306400/181702524-17ee7835-1b21-4e47-9d16-8d432411afb1.png)

 It would make it a lot more convenient for the users plus it can be automated to do regular backups. Not to mention there's an option for an encrypted backup file so it's really not that insecure

**Comment by RobertHarnett** [comment]
This has been [answered in the FAQ’s by the dev himself already](https://github.com/jamie-mh/AuthenticatorPro/wiki#frequently-asked-questions):

> Can you add sync to Google Drive, OneDrive, etc...
> 
> No. Syncing to cloud services would require the internet permission and heavy intrusive SDKs to support them. Also, they have a habit of changing the APIs often, which just requires more work.

Ultimately it’s up to them but I suspect the app is made intentionally to be as offline and secure as possible, while it could feasibly be done, I think it goes against the direction the dev want’s to take the app.

**Comment by Jnss98b** [comment]
That's understandable. Thank you for bringing attention to the faq. Idk how I missed that

**Comment by Mak0pog** [comment]
Alternatively, You can use DriveSync to backup the files from desired folder to Cloud.
