### ISSUE TITLE
Chrome OS Support

### ISSUE THREAD

**Issue by upD8R** [jamie-mh/AuthenticatorPro#504]
Hi there,

I don't know what it takes to make an app Chrome OS compatible but I can install the majority of my Android apps. Just Authenticator Pro is an exception here: Play Store claims it's not compatible with my device but it would be handy to have the codes available on my Chromebook, too.

(Currently I use Keepass as a workaround.)

Many thanks,
Mario

**Comment by jamie-mh** [comment]
Hi @upD8R ,

I don't have a Chromebook to test this on, but I believe this is due to the QR code scanning with the camera. According to [this page](https://developer.android.com/topic/arc/manifest#implied-features), Chromebooks cannot use the camera. I've marked the camera feature as not required, so hopefully this will be fixed in the next release.

Thanks

**Comment by upD8R** [comment]
Thanks, I'll let you know the outcome as soon as the new version is available.
