### ISSUE TITLE
Drop ACTION_OPEN_DOCUMENT_TREE

### ISSUE THREAD

**Issue by hj-collab** [jamie-mh/AuthenticatorPro#531]
Hi,

Please drop ACTION_OPEN_DOCUMENT_TREE and use ACTION_OPEN_DOCUMENT. So one drive / google drive show in file picker for automated authenticator pro backups. Aegis also faces the same issue. Take a look. https://github.com/beemdevelopment/Aegis/issues/848

**Comment by jamie-mh** [comment]
Hi,

A cursory look at this would suggest that it's not feasible for a couple of reasons:

- In order grant persistent permissions with ACTION_OPEN_DOCUMENT, the user must use ACTION_CREATE_DOCUMENT first. Selecting the same file twice is a little awkward to say the least.
- SAF providers such as Google Drive and Dropbox do not react well to overwriting a file multiple times. They tend to create many copies when they find conflicts.

On the local file system it would probably work fine, but since the target is cloud storage, it wouldn't work as suggested.

Cheers
