### ISSUE TITLE
feature request: backup encrypted HTML file

### ISSUE THREAD

**Issue by ftobin** [jamie-mh/AuthenticatorPro#66]
It would be very useful if one could export the secrets into an encrypted HTML file as a more reliable backup than the app-specific file format.  I can't feel safe backing up an unencrypted file, and the app-specific data makes me prone to app-specific issues if I need to recover data.

Ideally, the backup password would be, as the user's selection, be saved internally or requested on each backup.

My current authenticator, Authenticator Plus, allows one to export into an encrypted HTML file (encrypted zip using AES), asking for the password upon export.  It also allows one to do the app-specific backup (sqlite db) using a saved password, which I think is useful to prevent errors in re-entering the password.  (It uses two different passwords, which is silly, but the idea of retaining the password is a good one).  andOTP does similarly, saving the backup password (but into a json file).

**Comment by jamie-mh** [comment]
Hi @ftobin ,

The issue with AES encrypted zip files, is that the software support is limited as they are non-standard. AFAIK, the Windows file explorer doesn't work well with these files - anyone who tries this would rightly assume that their backup is messed up and they've lost their data.

I don't see how the current approach is different from the andOTP implementation. The app specific backup files are simply encrypted JSON files, their format is described [here](https://github.com/jamie-mh/AuthenticatorPro/blob/master/doc/BACKUP_FORMAT.md).

**Comment by ftobin** [comment]
Thank you for pointing out the decryption process of the app-specific backup through openssl, I hadn't seen that yet.  (As an aside on that, openssl seems to recommend that PBKDF2 be used.)

Just to be clear, I was not not advocating zip in particular (really 7z not zip), just that there was some better way of exporting the HTML format since that's the most useful by if needing to transfer between solutions.  More specifically, I think it would be excellent if users can export the HTML format encrypted in addition to the JSON, since it's much more useful in general.  I would never consider using the HTML export since transport off of the phone could be cumbersome to manage securely without exposing the data at any point.

Separately, I'll note out that that andOTP has a feature where it stores the backup pass internally and re-uses it, which can be very helpful from a reliability and security standpoint (I don't have to retrieve the password from a vault just to do a backup).   I could create this as separate feature request, I just brought it up here since it's part of the same use case.

**Comment by jamie-mh** [comment]
Yes, it appears that recent versions of OpenSSL recommend that a password derivation function is used instead of a hash, but the encryption is reasonably secure without it, so it's not really an issue.

Ultimately, it seems like this feature would be a step in the right direction in terms of security but a step backwards in terms of usability. Which is also why I was hesitant to add the HTML backup feature in the first place (issue #51). I don't think most people would know what to do with a 7zip file.

The reality is that OTP secrets just aren't as sensitive as passwords and the inconvenience / complexity of encrypting a HTML file in the app just doesn't seem worth it. I want the backup and restore process to be as frictionless as possible, so that everyone takes the time to do it. Yet again, I still receive emails from people who didn't bother to backup and are asking me to help recover their accounts. This may just worsen the problem. Sorry, but I don't think this is a good fit for the project at the moment.
