### ISSUE TITLE
Ability to have encrypted backup in Json or in compatible mode with other Apps.

### ISSUE THREAD

**Issue by fedonr** [jamie-mh/AuthenticatorPro#720]
I have been using this for a year now and love it so far. But as a tinker I like to switch apps and test it often. Though I'll keep using this app, but I have few dummy account which I use for testing that, I wanted to export. That is where it stuck me. If there can be a ability to export or backup the encrypted data which is compatible to be read and imported by other Apps like Aegis, Bitwarden etc. That would be great.

And it would also give the users peace of mind knowing they can switch securely with encryption when they like (if they want to), without feeling locked in.

**Comment by jamie-mh** [comment]
Hi,

The only formats that are de facto standards are QR code and URI list files. If you want to use another app, you can export to these formats, import your data and then delete them. If they were encrypted it would be a lot more complicated since everyone would need to agree on the encryption scheme and format. Unless an RFC comes along and defines a standard spec, I can't see that being possible.

Alternatively, you could export to one of these standard formats and encrypt it by some other means with VeraCrypt or a password-protected archive, for instance.

Cheers

**Comment by fedonr** [comment]
Awesome thanks, I'll look into VeraCrypt. BTW great app.
