### ISSUE TITLE
Biometric unlock, Fairphone 3, Update Android 13

### ISSUE THREAD

**Issue by HDValentin** [jamie-mh/AuthenticatorPro#895]
**Describe the bug**
I've updated my Fairphone to Android 13. Since the update, I can't unlock the Authenticator Pro app, no longer with fingerprint. Unlock screen of the app and in the settings >> biometric is blanked out and can't be set. Some other apps work with biometric, and android is unlockable by fingerprint.  Before updating to Android 13, everything worked well.

**To Reproduce**
1. Start the app
2. biometric is greyed out and not clickable
3. unlock only works via password.

**Expected behavior**
normal behavior as before. Biometric works.

**App Version**
1.21.0 F-Droid

**Additional context**
Fairphone 3+
Android 13

I've just seen that it is a Problem with the Security Class of the Fingerprint reader.
https://forum.fairphone.com/t/fairphone-3-and-3-a13-fingerprint-sensor-update/97654/347#previous-faqs-published-on-28th-of-july-16

I have a little hope that you have an idea how to solve this for the authentication app, perhaps with a workaround.

**Comment by jamie-mh** [comment]
Hi @HDValentin ,

Since the biometrics on your device is now [Class 2](https://source.android.com/docs/security/features/biometric/measure#biometric-classes), it can no longer be used to retrieve keys from the Android Keystore. This is a necessary part of the biometric unlock feature in Authenticator Pro.

Cheers
