### ISSUE TITLE
AltStore distribution for iOS

### ISSUE THREAD

**Issue by HOSEK1** [jamie-mh/AuthenticatorPro#903]
**Is your feature request related to a problem? Please describe.**
It's not available for iOS.

**Describe the solution you'd like**
Instead of using Apple's official appstore, you could use [AltStore](https://altstore.io/) instead for distribution.

I know that you already said that the app wont be available for iOS (Not sure if you own an apple device) but hey it's worth a shot to ask right? 
Thanks!

**Comment by ThatOneCalculator** [comment]
It's less of an issue with distribution and more of that this app was specifically written for Android.

**Comment by jamie-mh** [comment]
I don't plan to support iOS at this time. It would require a complete port, and I don't use any Apple devices personally.

**Comment by GlassedSilver** [comment]
Hey, totally understandable that you don't want to put in the effort when it'd probably be much of a complete rewrite to do it properly, but would you mind opening this discussion, so that dual-device users (and anyone with Android phones but on iPad for tablet usage) can get the best out of this app?

Having an authenticator specifically on just on platform is a bit of an iffy user experience and facilitating finding options that may not sync, but at least import Stratum databases would be incredibly useful.

Love the app to bits, especially because it's actively maintained AND has a WearOS app that isn't sketchy. Having SOME way to periodically carry over my 2FAs to iOS (and maybe Linux and macOS as well) without needing do that one by one would be really sweet. :)
