### ISSUE TITLE
Make App Display Name Translatable

### ISSUE THREAD

**Issue by Kvasenok** [jamie-mh/AuthenticatorPro#960]
Since the app's name is displayed simply as "Authenticator" and not "Authenticator Pro" it seems the point is to make it look on par wih the stock or google apps (like stock gallary or wallet) as most of these terms are translateble and not some untranslatable brand names.
Basically I see it this way: "Authenticator Pro" is the app's name shown in GP and anywhere else. "Authenticator" on the home screen under the app's icon is app's descriptory function, i.e. "an app with authenticators", and so I believe it should be translatable like "Gallery", "Files", "Camera" etc.
If the word itself is impossible to translate into some specific language it can always be translated as "Authenticator" on CrowdIn, as it is now.

I can probably do it myself and submit a PR if I understand the code correctly, but I still need an approval.

**Comment by jamie-mh** [comment]
I see what you mean. However, Google Authenticator for instance shows the word "Authenticator" in both English and French. I prefer not to translate it in the French version because I think it looks a bit awkward, and I think of it as a shorthand version of "Authenticator Pro".

In what language do you think it should be translated?

Cheers

**Comment by jamie-mh** [comment]
Okay, it probably makes sense to keep the text "Authenticator" for now.
